config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: %i[sessions registrations], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get '/homepage', to: 'page#homepage'
    resources :teachers, only: %i[index show]
  end

  devise_for :teachers, only: %i[sessions registrations], controllers: {
    sessions: 'teachers/sessions'
  }
  namespace :teachers do
    get '/homepage', to: 'page#homepage'
    resources :students
    resources :courses, only: %w[index show]
    patch 'update_avatar', to: 'avatar#update_avatar'
    get 'edit_avatar', to: 'avatar#edit_avatar'
  end

  devise_for :students, controllers: {
    sessions: 'students/sessions'
  }

  namespace :students do
    resources :courses do
      resources :enrollments, only: [:create]
    end
    get 'all_courses', to: 'enrollments#index'
    get '/homepage', to: 'page#homepage'
  end

  get 'homepage', to: 'home#homepage'
  root to: redirect('/homepage')

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :age, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < Admin
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_one_attached :avatar
end

app/models/teacher.rb
class Teacher < Admin
  has_one_attached :avatar
end

app/controllers/admins/admins_controller.rb
class Admins::AdminsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/page_controller.rb
class Admins::PageController < Admins::AdminsController
  def homepage
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  before_action :check_admin

  private

  def check_admin
    if current_student
      redirect_to students_homepage_path, alert: 'Unauthorized access for student'
    elsif current_teacher
      redirect_to teachers_homepage_path, alert: 'Unauthorized acces for teacher'
    end
  end
end

app/controllers/admins/teachers_controller.rb
class Admins::TeachersController < Admins::AdminsController
  def index
    @teachers = Teacher.where(role: 'teacher')
  end

  def show
    @teacher = Teacher.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :admin_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource.type
    when 'Teacher'
      teachers_homepage_path
    when 'Student'
      students_homepage_path
    end
  end

  private

  def admin_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name age role])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name age role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end
end

app/controllers/students/courses_controller.rb
class Students::CoursesController < Students::StudentsController
  def index
    @courses = Course.all
  end
end

app/controllers/students/enrollments_controller.rb
class Students::EnrollmentsController < Students::StudentsController
  def index
    # debugger
    @enrollments = current_student.enrollments.includes(:course)
  end

  def create
    @enollment = current_student.enrollments.new
    @enollment.course_id = params[:course_id]
    if @enollment.save
      redirect_to students_all_courses_path, notice: 'Enrolled successfully'
    else
      redirect_to students_courses_path, alert: 'Something went wrong....'
    end
  end
end

app/controllers/students/page_controller.rb
class Students::PageController < Students::StudentsController
  def homepage
    # debugger
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  before_action :check_student

  private

  def check_student
    if current_teacher || current_admin
      if current_admin
        redirect_to admins_homepage_path, alert: 'Unauthorizedsssss access.'
      elsif current_teacher
        redirect_to teachers_homepage_path, alert: 'Unauthorizedsssss access.'
      end
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/students_controller.rb
class Students::StudentsController < ApplicationController
  before_action :authenticate_student!
end

app/controllers/teachers/avatar_controller.rb
class Teachers::AvatarController < Teachers::TeachersController

  def edit_avatar
  end

  def update_avatar
    unless params[:avatar].present?
      redirect_to teachers_edit_avatar_path, alert: 'select and image'
      return
    end
    if current_teacher.avatar.attach(params[:avatar])
      redirect_to teachers_edit_avatar_path, notice: 'Uploaded the image successfully!!!!'
    else
      redirect_to teachers_edit_avatar_path, alert: 'Some thing gone wrong'
    end
  end

  private

  def set_avatar_params
    params.require(:teacher).permit(:avatar)
  end
end

app/controllers/teachers/courses_controller.rb
class Teachers::CoursesController < Teachers::TeachersController
  before_action :set_course, only: %w[show]
  def index
    @courses = Course.includes(:students)
  end

  def show
    @students = @course.students
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/teachers/page_controller.rb
class Teachers::PageController < Teachers::TeachersController
  def homepage
  end
end

app/controllers/teachers/sessions_controller.rb
class Teachers::SessionsController < Devise::SessionsController
  before_action :check_teacher

  private

  def check_teacher
    if current_admin || current_student
      if current_student
        redirect_to students_homepage_path, alert: 'Unauthorized access for student'
      elsif current_admin
        redirect_to admins_homepage_path, alert: 'Unauthorized access for admin page'
      end
    end
  end
end

app/controllers/teachers/students_controller.rb
class Teachers::StudentsController < Teachers::TeachersController
  def index
    # debugger
    @students = Student.includes(enrollments: :course)
    # debugger
    # course=[]
    # debugger
    # si.enrollments.each { |n| << Course.find_by(id: n.course_id).name }
  end
end

app/controllers/teachers/teachers_controller.rb
class Teachers::TeachersController < ApplicationController
  before_action :authenticate_teacher!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/students/courses/index.html.haml
-# .container{style: 'width: 100%'}
%div
  .row.gap-2.d-flex.justify-content-around
    - @courses.each do |course|
      .col-sm-5.col-lg-3.col-xxl-2.mt-1.mb-2
        .card.border.border-black.w-100{style: 'min-height: 250px; min-width: 200px'}
          .card-header 
            = course.name
          .card-body.d-flex.justify-content-between.flex-column
            = course.description
            - if current_student.enrollments.exists?(course_id: course.id)
              %p Enrolled
            - else 
              = button_to 'Enroll', students_course_enrollments_path(course), class: 'btn btn-primary text-black'
            

app/views/students/enrollments/index.html.haml
%h1 Enrolled courses
%table.table
  %thead
    %tr
      %th Name
      %th Description
  %tbody
    - @enrollments.each do |enrollment|
      %tr
        %td= enrollment.course.name
        %td= enrollment.course.description

app/views/students/page/homepage.html.haml
Welcome to student homepage

-# - if student_signed_in?
	-# .btn.btn-primary.btn-sm 
= button_to 'Delete', destroy_student_session_path, method: :delete, class: 'btn btn-primary'

app/views/teachers/avatar/edit_avatar.html.haml
=form_with model: @avatar, url: teachers_update_avatar_path, method: :patch do |f|
  =f.label :avatar
  =f.file_field :avatar
  =f.submit

- if current_teacher.avatar.attached?
  = image_tag(current_teacher.avatar, style: 'height: 200px; width: 200px; border-radius: 50% ')

app/views/teachers/page/homepage.html.haml
Welcome to teacher homepage
- if teacher_signed_in?
	-# .btn.btn-primary.btn-sm 
	= button_to 'Delete', destroy_admin_session_path, method: :delete, class: 'btn btn-primary'

app/views/teachers/students/index.html.haml
%h1 All Students
%table.table
  %thead
    %tr
      %th Name
      %th Email
      %th Age
      %th Courses Enrolled
  %tbody
    - @students.each do |student|
      %tr
        %td= student.name
        %td= student.email
        %td= student.age
        - course = []
        -# - student.enrollments.each { |n| courses<< n.name}
        -# - if courses.empty?
        -#   %td No enrolled courses
        -# - else
        -#   %td= courses.join(', ')
        - courses = student.enrollments.map { |enrollment| enrollment.course.name }
        - if courses.empty?
          %td No enrolled courses
        - else
          %td= courses.join(', ')