config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: %i[sessions registrations], controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    get '/homepage', to: 'page#homepage'
    resources :teachers, only: %i[index show]
  end

  devise_for :teachers, only: %i[sessions registrations], controllers: {
    sessions: 'teachers/sessions'
  }
  namespace :teachers do
    get '/homepage', to: 'page#homepage'
    resources :students
    resources :courses, only: %w[index show]
    patch 'update_avatar', to: 'avatar#update_avatar'
    get 'edit_avatar', to: 'avatar#edit_avatar'
  end

  devise_for :students, controllers: {
    sessions: 'students/sessions'
  }

  namespace :students do
    resources :courses do
      resources :enrollments, only: [:create]
    end
    get 'all_courses', to: 'enrollments#index'
    get '/homepage', to: 'page#homepage'
  end

  get 'homepage', to: 'home#homepage'
  root to: redirect('/homepage')

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :age, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < Admin
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_one_attached :avatar
end

app/models/teacher.rb
class Teacher < Admin
  has_one_attached :avatar
end

app/controllers/admins/admins_controller.rb
class Admins::AdminsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/page_controller.rb
class Admins::PageController < Admins::AdminsController
  def homepage
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  before_action :check_admin

  private

  def check_admin
    if current_student
      redirect_to students_homepage_path, alert: 'Unauthorized access for student'
    elsif current_teacher
      redirect_to teachers_homepage_path, alert: 'Unauthorized acces for teacher'
    end
  end
end

app/controllers/admins/teachers_controller.rb
class Admins::TeachersController < Admins::AdminsController
  def index
    @teachers = Teacher.where(role: 'teacher')
  end

  def show
    @teacher = Teacher.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :admin_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource.type
    when 'Teacher'
      teachers_homepage_path
    when 'Student'
      students_homepage_path
    end
  end

  private

  def admin_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name age role])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name age role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end
end

app/controllers/students/courses_controller.rb
class Students::CoursesController < Students::StudentsController
  def index
    @courses = Course.all
  end
end

app/controllers/students/page_controller.rb
class Students::PageController < Students::StudentsController
  def homepage
    # debugger
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  before_action :check_student

  private

  def check_student
    if current_teacher || current_admin
      if current_admin
        redirect_to admins_homepage_path, alert: 'Unauthorizedsssss access.'
      elsif current_teacher
        redirect_to teachers_homepage_path, alert: 'Unauthorizedsssss access.'
      end
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teachers/avatar_controller.rb
class Teachers::AvatarController < Teachers::TeachersController

  def edit_avatar
  end

  def update_avatar
    unless params[:avatar].present?
      redirect_to teachers_edit_avatar_path, alert: 'select and image'
      return
    end
    if current_teacher.avatar.attach(params[:avatar])
      redirect_to teachers_edit_avatar_path, notice: 'Uploaded the image successfully!!!!'
    else
      redirect_to teachers_edit_avatar_path, alert: 'Some thing gone wrong'
    end
  end

  private

  def set_avatar_params
    params.require(:teacher).permit(:avatar)
  end
end

app/controllers/teachers/courses_controller.rb
class Teachers::CoursesController < Teachers::TeachersController
  before_action :set_course, only: %w[show]
  def index
    @courses = Course.includes(:students)
  end

  def show
    @students = @course.students
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/teachers/page_controller.rb
class Teachers::PageController < Teachers::TeachersController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/page/homepage.html.haml
Welcome to admin homepage

- if admin_signed_in?
	-# .btn.btn-primary.btn-sm 
	= button_to 'Delete', destroy_admin_session_path, method: :delete, class: 'btn btn-primary'

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_admin_menu.html.haml
%button#side-button.btn.btn-light.mb-2
	= link_to 'All teachers', admins_teachers_path
%button#side-button.btn.btn-light.mb-2 sad
%button#side-button.btn.btn-light Button 3

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.position-fixed
  .container-fluid
    %a.navbar-brand{href: "#"} MyLms
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav.ms-auto
        %li.nav-item
          = link_to 'Home', root_path, class: 'nav-link'
        - if current_admin
          %li.nav-item
            = link_to 'Admin Dashboard', class: 'nav-link'
        - elsif current_teacher
          %li.nav-item
            = link_to 'Teacher Dashboard',  class: 'nav-link'
        - elsif current_student
          %li.nav-item
            = link_to 'Student Dashboard',class: 'nav-link'

app/views/partials/_sidebar.html.haml
.sidebar.bg-dark.text-white
  .p-3
    / Application Name
    %h4.mb-4 My Application
    / Sidebar Buttons
    - if current_admin
      = render 'partials/admin_menu'
    - if current_teacher
      = render 'partials/teacher_menu'
    - if current_student
      = render 'partials/student_menu'

app/views/partials/_student_menu.html.haml
%button#side-button.btn.btn-light.mb-2
	= link_to 'All courses', students_courses_path
%button#side-button.btn.btn-light.mb-2= link_to 'Enrolled course', students_all_courses_path
%button#side-button.btn.btn-light Button 3

app/views/partials/_teacher_menu.html.haml
%button#side-button.btn.btn-light.mb-2
	= link_to 'All student', teachers_students_path
%button#side-button.btn.btn-light.mb-2 
	= link_to 'All subject', teachers_courses_path
%button#side-button.btn.btn-light
	= link_to 'Edit avatar', teachers_edit_avatar_path